### ISSUE TITLE
Features / Roadmap

### ISSUE THREAD

**Issue by luan** [luan/slenderaac#24]
### Website

- [x] Account management
- [x] Account recovery
- [x] Character management
- [x] Character search
- [x] Highscores
- [x] News
- [x] Static pages
- [x] Coin shop
- [x] I18n (currently only English)
- [x] Animated outfits
- [x] Boosted creature / boss
- [x] Server status
- [x] Who's online
- [x] Themable
- [x] Dark mode
- [x] Responsive design
- [x] Mobile friendly
- [x] Highly secure bcrypt based password hashing
- [x] Account verification
- [x] Two factor auth
- [x] Guild management
- [ ] Character inventory
- [ ] Server save countdown
- [ ] Guild wars
- [ ] Multi-world
- [ ] Char bazaar
- [ ] Houses
- [ ] Recent deaths
- [ ] Kill statistics
- [ ] Power gamers
- [ ] World map

### Admin panel

- [x] News management ([markdoc](https://markdoc.dev))
- [x] Static pages management ([markdoc](https://markdoc.dev))
- [x] Easily create first admin account (`AUTO_ADMIN_EMAIL`)
- [ ] Account management
- [ ] Character management
- [ ] Guild management
- [ ] House management
- [ ] Server management
- [ ] Server logs
- [ ] Server configuration
- [ ] Guided installer

### API

- [x] Login
- [x] Login via expiring session for increased security
- [x] Boosted creature / boss
- [x] Online counts
- [ ] Compendium API
- [ ] Events API
- [ ] Other APIs (for discord integration, etc)
